# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniquePerson',
            new_name='Person',
        ),
        migrations.RenameModel(
            old_name='SimpleDayRecord',
            new_name='Record',
        ),
    ]
